<span metal:use-macro="camp/header.phtml/header" />

<tal:block condition="exists: camp/getOwner">
	<h2>Owner:</h2>
</tal:block>



<h2>Manager:</h2>

<tal:block repeat="usercamp managers">
	<span metal:use-macro="global/singleuser.phtml/withavatar" tal:define="user usercamp/getUser" tal:omit-tag="" />
</tal:block>
<div class="clear" />



<h2>Leader:</h2>

<tal:block repeat="usercamp leaders">
	<span metal:use-macro="global/singleuser.phtml/withavatar" tal:define="user usercamp/getUser" tal:omit-tag="" />
</tal:block>
<div class="clear" />



<h2>Guest:</h2>

<tal:block repeat="usercamp guests">
	<span metal:use-macro="global/singleuser.phtml/withavatar" tal:define="user usercamp/getUser" tal:omit-tag="" />
</tal:block>
<div class="clear" />

<h2>Invite:</h2>

<tal:block repeat="user twoUser">
	<div>
		<span metal:use-macro="global/singleuser.phtml/withavatar" tal:define="user user" tal:omit-tag="" />
		<a class="button positive" tal:attributes="href helper:campurl(camp, array('controller' => 'leader', 'action' => 'invite', 'invitedUser' => user.getId(), 'role' => 50), 'camp')">Invite</a>
	</div>
</tal:block>
<div class="clear" />

<!-- 
	Todo UseCase:
	
	Add a list of suggested Users to be invited to this camp
 -->